x-airflow-common: &airflow-common
  image: apache/airflow:3.2.2
  environment:
    AIRFLOW__DATABASE__SQL_ALCHEMY_CONN: postgresql+psycopg2://${POSTGRES_USER}:${POSTGRES_PASSWORD}@postgres/airflow
    AIRFLOW__CORE__EXECUTOR: LocalExecutor
    AIRFLOW__CORE__LOAD_EXAMPLES: "false"
    AIRFLOW__API__SECRET_KEY: ${AIRFLOW_SECRET_KEY}
    AIRFLOW__CORE__AUTH_MANAGER: airflow.providers.fab.auth_manager.fab_auth_manager.FabAuthManager
    AIRFLOW__CORE__EXECUTION_API_SERVER_URL: http://news_airflow_webserver:8080/execution/
    AIRFLOW__API_AUTH__JWT_SECRET: ${AIRFLOW_SECRET_KEY}
    POSTGRES_HOST: postgres
    POSTGRES_PORT: 5432
    POSTGRES_DB: ${POSTGRES_DB}
    POSTGRES_USER: ${POSTGRES_USER}
    POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    EMBED_MODEL: ${EMBED_MODEL}
    SPARK_MASTER_URL: spark://spark-master:7077
    SPARK_JOBS_PATH: /opt/airflow/spark/jobs
    PG_JAR_PATH: /opt/spark/jars/postgresql-42.7.3.jar
  volumes:
    - ./backend/airflow/dags:/opt/airflow/dags
    - ./backend/spark:/opt/airflow/spark
    - airflow_logs:/opt/airflow/logs
    - /var/run/docker.sock:/var/run/docker.sock
  networks:
    - news_net

services:

  postgres:
    build:
      context: ./db
      dockerfile: Dockerfile
    container_name: news_postgres
    restart: always
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./db/init-airflow.sql:/docker-entrypoint-initdb.d/init-airflow.sql
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "${POSTGRES_USER}", "-d", "${POSTGRES_DB}"]
      interval: 10s
      retries: 5
    networks:
      - news_net

  spark-master:
    build:
      context: ./backend/spark
    container_name: news_spark_master
    restart: always
    command: /opt/spark/bin/spark-class org.apache.spark.deploy.master.Master
    environment:
      POSTGRES_HOST: postgres
      POSTGRES_PORT: 5432
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      EMBED_MODEL: ${EMBED_MODEL}
    ports:
      - "7077:7077"
      - "8081:8080"
    volumes:
      - ./backend/spark/jobs:/opt/spark/jobs
      - spark_model_cache:/root/.cache/huggingface
    networks:
      - news_net
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080"]
      interval: 30s
      timeout: 10s
      retries: 3

  spark-worker:
    build:
      context: ./backend/spark
    container_name: news_spark_worker
    restart: always
    command: /opt/spark/bin/spark-class org.apache.spark.deploy.worker.Worker spark://spark-master:7077
    environment:
      SPARK_WORKER_MEMORY: ${SPARK_WORKER_MEMORY:-2g}
      SPARK_WORKER_CORES: ${SPARK_WORKER_CORES:-2}
      POSTGRES_HOST: postgres
      POSTGRES_PORT: 5432
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      EMBED_MODEL: ${EMBED_MODEL}
    volumes:
      - ./backend/spark/jobs:/opt/spark/jobs
      - spark_model_cache:/root/.cache/huggingface
    depends_on:
      spark-master:
        condition: service_healthy
    networks:
      - news_net

  airflow-webserver:
    <<: *airflow-common
    container_name: news_airflow_webserver
    restart: always
    command: >
      bash -c "
        pip install apache-airflow-providers-fab feedparser psycopg2-binary &&
        airflow db migrate &&
        airflow users create --username ${AIRFLOW_USER} --password ${AIRFLOW_PASSWORD} --firstname Admin --lastname User --role Admin --email ${AIRFLOW_EMAIL} || true &&
        airflow api-server
      "
    ports:
      - "8080:8080"
    depends_on:
      postgres:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "curl", "--fail", "http://localhost:8080/api/v2/monitor/health"]
      interval: 30s
      retries: 5

  airflow-dag-processor:
    <<: *airflow-common
    container_name: news_airflow_dag_processor
    restart: always
    command: bash -c "pip install feedparser psycopg2-binary && airflow db migrate && airflow dag-processor"
    depends_on:
      airflow-webserver:
        condition: service_healthy

  airflow-scheduler:
    <<: *airflow-common
    container_name: news_airflow_scheduler
    restart: always
    command: bash -c "pip install feedparser psycopg2-binary && airflow db migrate && airflow scheduler"
    depends_on:
      airflow-webserver:
        condition: service_healthy

  fastapi:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: news_fastapi
    restart: always
    environment:
      POSTGRES_HOST: postgres
      POSTGRES_PORT: 5432
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      GEMINI_API_KEY: ${GEMINI_API_KEY}
      EMBED_MODEL: ${EMBED_MODEL}
      AIRFLOW_SECRET_KEY: ${AIRFLOW_SECRET_KEY}
      LANG: C.UTF-8
      LC_ALL: C.UTF-8
      PYTHONIOENCODING: utf-8
    volumes:
      - ./backend:/app
    ports:
      - "8000:8000"
    depends_on:
      postgres:
        condition: service_healthy
    networks:
      - news_net

volumes:
  postgres_data:
  airflow_logs:
  spark_model_cache:

networks:
  news_net:
    driver: bridge